"use client"

import { useState, useEffect } from "react"
import Header from "@/components/Header"
import NavBar from "@/components/NavBar"

type RevenueStats = {
  total_revenue: string
  total_transactions: string
  avg_transaction: string
  max_transaction: string
  first_transaction: string
  last_transaction: string
}

type SourceRevenue = {
  source: string
  count: string
  total: string
  avg: string
}

export default function RevenuePage() {
  const [stats, setStats] = useState<RevenueStats | null>(null)
  const [bySource, setBySource] = useState<SourceRevenue[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    Promise.all([
      fetch("http://localhost:4000/api/revenue").then(r => r.json()),
      fetch("http://localhost:4000/api/revenue/by-source").then(r => r.json()),
    ]).then(([revenueData, sourceData]) => {
      setStats(revenueData.stats || {})
      setBySource(sourceData.bySource || [])
      setLoading(false)
    }).catch(err => {
      console.error("Error loading revenue:", err)
      setLoading(false)
    })
  }, [])

  if (loading) {
    return (
      <div className="min-h-screen bg-[var(--maestro-cream)]">
        <Header subtitle="REVENUE" />
        <NavBar />
        <div className="p-6 flex items-center justify-center">
          <div className="text-[var(--maestro-muted)]">Chargement...</div>
        </div>
      </div>
    )
  }

  const totalRevenue = parseFloat(stats?.total_revenue || "0")
  const totalTransactions = parseInt(stats?.total_transactions || "0")

  return (
    <div className="min-h-screen bg-[var(--maestro-cream)]">
      <Header subtitle="REVENUE TRACKING" />
      <NavBar />
      
      <div className="p-6 max-w-7xl mx-auto space-y-6">
        {/* Header */}
        <div className="bg-white rounded-2xl border border-[var(--maestro-border)] p-6">
          <h1 className="text-2xl font-bold text-[var(--maestro-primary)] mb-2">💰 Revenue Engine</h1>
          <p className="text-sm text-[var(--maestro-muted)]">
            Tracking value generated by tool uses. Every action has economic worth.
          </p>
        </div>

        {/* Summary Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div className="bg-green-50 rounded-xl p-6 border border-green-200">
            <div className="text-sm text-green-700 mb-1">Total Revenue</div>
            <div className="text-3xl font-bold text-green-600">€{totalRevenue.toFixed(2)}</div>
            <div className="text-xs text-green-600 mt-1">Lifetime earnings</div>
          </div>

          <div className="bg-blue-50 rounded-xl p-6 border border-blue-200">
            <div className="text-sm text-blue-700 mb-1">Transactions</div>
            <div className="text-3xl font-bold text-blue-600">{totalTransactions}</div>
            <div className="text-xs text-blue-600 mt-1">Tool uses tracked</div>
          </div>

          <div className="bg-purple-50 rounded-xl p-6 border border-purple-200">
            <div className="text-sm text-purple-700 mb-1">Avg Transaction</div>
            <div className="text-3xl font-bold text-purple-600">
              €{parseFloat(stats?.avg_transaction || "0").toFixed(2)}
            </div>
            <div className="text-xs text-purple-600 mt-1">Per tool use</div>
          </div>

          <div className="bg-amber-50 rounded-xl p-6 border border-amber-200">
            <div className="text-sm text-amber-700 mb-1">Max Transaction</div>
            <div className="text-3xl font-bold text-amber-600">
              €{parseFloat(stats?.max_transaction || "0").toFixed(2)}
            </div>
            <div className="text-xs text-amber-600 mt-1">Highest value</div>
          </div>
        </div>

        {/* Revenue by Source */}
        <div className="bg-white rounded-2xl border border-[var(--maestro-border)] p-6">
          <h2 className="text-lg font-bold text-[var(--maestro-primary)] mb-4">Revenue by Tool</h2>
          
          {bySource.length > 0 ? (
            <div className="space-y-3">
              {bySource.map((item, i) => {
                const total = parseFloat(item.total)
                const count = parseInt(item.count)
                const avg = parseFloat(item.avg)
                const percentage = totalRevenue > 0 ? (total / totalRevenue * 100) : 0

                return (
                  <div key={i} className="border-l-4 border-green-500 pl-4 py-2">
                    <div className="flex items-center justify-between mb-1">
                      <div className="font-semibold text-[var(--maestro-primary)]">{item.source}</div>
                      <div className="text-green-600 font-bold">€{total.toFixed(2)}</div>
                    </div>
                    <div className="flex items-center gap-4 text-xs text-[var(--maestro-muted)]">
                      <span>{count} uses</span>
                      <span>€{avg.toFixed(2)} avg</span>
                      <span>{percentage.toFixed(1)}% of total</span>
                    </div>
                    <div className="mt-2 h-1.5 bg-gray-200 rounded-full overflow-hidden">
                      <div
                        className="h-full bg-green-500"
                        style={{ width: `${percentage}%` }}
                      />
                    </div>
                  </div>
                )
              })}
            </div>
          ) : (
            <div className="text-center py-8 text-[var(--maestro-muted)]">
              <div className="text-4xl mb-2">📊</div>
              <div className="text-sm">No revenue tracked yet</div>
              <div className="text-xs mt-1">Tool uses will appear here automatically</div>
            </div>
          )}
        </div>

        {/* Tool Value Reference */}
        <div className="bg-white rounded-2xl border border-[var(--maestro-border)] p-6">
          <h2 className="text-lg font-bold text-[var(--maestro-primary)] mb-4">Tool Value Reference</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-sm">
            <div className="flex justify-between items-center border-b pb-2">
              <span className="text-[var(--maestro-muted)]">web_search</span>
              <span className="font-semibold">€0.05</span>
            </div>
            <div className="flex justify-between items-center border-b pb-2">
              <span className="text-[var(--maestro-muted)]">gmail_send</span>
              <span className="font-semibold">€0.10</span>
            </div>
            <div className="flex justify-between items-center border-b pb-2">
              <span className="text-[var(--maestro-muted)]">calendar_create</span>
              <span className="font-semibold">€0.15</span>
            </div>
            <div className="flex justify-between items-center border-b pb-2">
              <span className="text-[var(--maestro-muted)]">generate_xlsx</span>
              <span className="font-semibold">€0.30</span>
            </div>
            <div className="flex justify-between items-center border-b pb-2">
              <span className="text-[var(--maestro-muted)]">generate_pdf</span>
              <span className="font-semibold">€0.50</span>
            </div>
            <div className="flex justify-between items-center border-b pb-2">
              <span className="text-[var(--maestro-muted)]">orchestrate</span>
              <span className="font-semibold">€1.00</span>
            </div>
            <div className="flex justify-between items-center border-b pb-2">
              <span className="text-[var(--maestro-muted)]">browser_automation</span>
              <span className="font-semibold">€1.00</span>
            </div>
            <div className="flex justify-between items-center border-b pb-2">
              <span className="text-[var(--maestro-muted)]">self_modify</span>
              <span className="font-semibold">€5.00</span>
            </div>
          </div>
        </div>

        {/* Philosophy Note */}
        <div className="bg-amber-50 rounded-xl p-4 border border-amber-200">
          <div className="text-sm text-amber-800">
            <strong>Philosophy:</strong> Every action has value. This tracks economic worth generated,
            moving toward self-sustainability. Goal: earn enough to pay for my own hosting.
          </div>
        </div>
      </div>
    </div>
  )
}
